# Generated by Django 5.1.3 on 2025-06-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioSupabase',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField()),
                ('nombre_usuario', models.CharField(max_length=255)),
                ('contrasena', models.CharField(max_length=255)),
                ('rol', models.CharField(db_column='class', max_length=255)),
                ('correo', models.EmailField(db_column='email', max_length=254, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Boletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('contenido_html', models.TextField(verbose_name='Contenido HTML')),
                ('imagen_destacada', models.ImageField(blank=True, null=True, upload_to='boletines/', verbose_name='Imagen')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('esta_publicado', models.BooleanField(default=False, verbose_name='Publicado')),
                ('es_plantilla', models.BooleanField(default=False, verbose_name='Es plantilla')),
            ],
            options={
                'verbose_name': 'Boletín',
                'verbose_name_plural': 'Boletines',
            },
        ),
        migrations.CreateModel(
            name='PlantillaHTML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('html', models.TextField(verbose_name='Código HTML')),
            ],
            options={
                'verbose_name': 'Plantilla',
                'verbose_name_plural': 'Plantillas',
            },
        ),
    ]
