# Generated by Django 5.1.3 on 2025-06-20 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fuente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('etiquetas', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('articulos', models.ManyToManyField(to='buscador_fuentes.articulo')),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='fuente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buscador_fuentes.fuente'),
        ),
    ]
